dist: xenial
language: python
python: 3.7

git:
  depth: false

before_install:
  - sudo rm -f /etc/boto.cfg

# safe list
branches:
  only:
  - master

install:
  - pip install -r requirements.txt

script:
  - pylint $TRAVIS_BUILD_DIR/src/lambda_function/function.py
  - cd $TRAVIS_BUILD_DIR/src
  - python -m pytest $TRAVIS_BUILD_DIR/tests --cov-report term --cov=lambda_function/function.py
  - cd ..
  - python setup.py ldist --include-version=False

deploy:
  provider: lambda
  function_name: $NEW_MUSIC_EMAILER_FUNCTION_NAME
  region: "us-east-1"
  role: $NEW_MUSIC_EMAILER_ROLE
  handler_name: "handler"
  runtime: "python3.7"
  zip: $TRAVIS_BUILD_DIR/dist/new-music-emailer.zip